# 开发环境配置
#service:
#  #端口号
#  port: 3000
#  #项目名,如果不设定，默认为/
#  context-path: /blog
spring:
  profiles:
    active: druids

mybatis:
  #实体类所在包
  type-aliases-package: com.sxjf.blog.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/*.xml
  #加载全局的配置文件
  #config-location: classpath:mybatis/mybatis-config.xml